# Generated by Django 4.2.20 on 2025-03-24 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_member_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='documento',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
