# Generated by Django 5.1.6 on 2025-03-07 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Equipments',
            new_name='Equipment',
        ),
    ]
