# Generated by Django 4.2.20 on 2025-03-18 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='foto',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
